pages:
    stage: deploy
    
    script:
    - mkdir .public
    - cp -a dist/. .public
    - mv .public public
    - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -exec gzip -f

    artifacts:
        paths:
        - public
    
    only:
    - master
