# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
image: node:10.15.3

pages:
    cache:
        paths:
        - node_modules/

    stage: deploy
    
    script:
    - mkdir .public
    - cp -r * .public
    - mv .public public
    - yarn install
    
    artifacts:
        paths:
        - public
    
    only:
    - master
