# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
image: node:9.11.1

pages:
    cache:
        paths:
        - node_modules/

    stage: deploy
    
    script:
    - mkdir .public
    - cp -r * .public
    - mv .public public
    - yarn install
    - yarn build
    artifacts:
    
    paths:
    - public
    
    only:
    - master
