pages:
    script:
    - mkdir .public
    - cp dist .public
    - mv .public public
    - yarn install

    artifacts:
        paths:
        - public

    only:
    - master

    stage:
    - deploy